language: java
services:
  - postgresql
before_script:
  - psql -c 'create database archive;' -U postgres
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
