/* Define database schema here */
CREATE TABLE BOOK (
    ID SERIAL,
    TITLE VARCHAR(200) NOT NULL,
    WRITER VARCHAR(200) NOT NULL,
    ISBN VARCHAR(50),
    DESCRIPTION VARCHAR(1000),
    IS_READ BOOLEAN,
    DATE_OF_READ TIMESTAMP,
    PRIMARY KEY (ID)
);
