INSERT INTO BOOK (WRITER, TITLE, ISBN, IS_READ) VALUES ('Robert Martin', 'Clean Code: A Handbook of Agile Software Craftsmanship', '978-0132350884', FALSE);
INSERT INTO BOOK (WRITER, TITLE, ISBN, IS_READ, DATE_OF_READ) VALUES ('Dennis M. Ritchie', 'C Programming Language', '0-13-110370-9', TRUE, TIMESTAMP '2011-05-16 15:36:38');

INSERT INTO TAG (NAME) VALUES ('style');
INSERT INTO TAG (NAME) VALUES ('language');
INSERT INTO TAG (NAME) VALUES ('legacy');

INSERT INTO BOOK_TAG(BOOK_ID, TAG_ID) VALUES (1, 1);
INSERT INTO BOOK_TAG (BOOK_ID, TAG_ID) VALUES (2, 2);
INSERT INTO BOOK_TAG (BOOK_ID, TAG_ID) VALUES (2, 3);


